### ISSUE TITLE
handleAuthRequestWithProfiles doesnt work

### ISSUE THREAD

**Issue by sirpy** [0xPolygonID/js-sdk-examples#20]
When running `npm run start handleAuthRequestWithProfiles`
I get the following error:
````
Error: Error: Assert Failed.
Error in template ForceEqualIfEnabled_234 line: 56
Error in template SMTVerifier_411 line: 134
Error in template AuthV2_426 line: 99

    at /Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@iden3/js-jwz/dist/node/cjs/witness_calculator.js:156:27
    at Array.forEach (<anonymous>)
    at WitnessCalculator._doCalculateWitness (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@iden3/js-jwz/dist/node/cjs/witness_calculator.js:130:14)
    at WitnessCalculator.calculateWTNSBin (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@iden3/js-jwz/dist/node/cjs/witness_calculator.js:193:20)
    at prove (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@iden3/js-jwz/dist/node/cjs/common.js:15:47)
    at async ProvingMethodGroth16AuthV2.prove (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@iden3/js-jwz/dist/node/cjs/authV2Groth16.js:27:25)
    at async Token.prove (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@iden3/js-jwz/dist/node/cjs/jwz.js:108:23)
    at async ZKPPacker.pack (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/iden3comm/packers/zkp.js:99:26)
    at async PackageManager.pack (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/iden3comm/packageManager.js:33:16)
    at async AuthHandler.handleAuthorizationRequest (/Users/hadarro/workspace/GoodDollar/GoodID/packages/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/iden3comm/handlers/auth.js:168:50)
````

**Comment by sirpy** [comment]
@vmidyllic another witness issue
