### ISSUE TITLE
Transit State method fails

### ISSUE THREAD

**Issue by Sshovon** [0xPolygonID/js-sdk-examples#28]
Getting following error when invoking transit state for mtp creds, 
```
/home/frcs/polygon/js-sdk-examples/node_modules/ethers/src.ts/utils/errors.ts:694
            error = new Error(message);
                    ^
Error: could not coalesce error (error={ "code": -32000, "message": "transaction underpriced: tip needed 30000000000, tip permitted 1000000000" }, payload={ "id": 10, "jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": [ "0x02f901f48301388204843b9aca00843b9aca1e83228304941a4cc30f2aa0377b0c3bc9848766d90cb440412480b9018428f88a65000d4d2b889f814f2ee2e00869baff56c4a6cc125d57aa373ecbbc06f90513022b889f814f2ee2e00869baff56c4a6cc125d57aa373ecbbc06f90519f511b6840cd3161b348c2d7546d688222f55ac23388db741991016182617ff5333fb646600000000000000000000000000000000000000000000000000000000000000011d2e6793d383d81ce434d528d3dc00128f7272b7fc20ac9884d904b182516cfb1bcfa869ec391d07bb7e78c710711674f518141c3e5dc8573b81961b1d48c5201aa56a0825d0405d8376041f725666df5fe6fb026a1a75c3fe6071fb4748f10621cffb34b147253ab1cc05a9f3f6558bc427a609a3646cdd06e849eb8e63a4d514c666335828b6d1402a43d53baba4adef24c68e6169741d0e4d6fe0caf6e3ad04e874227824bc7c75dc2fc26925ade294f0803c5cb473ee6aa117e967e053e126aa05e5ae9ca71f9b63568b5c7f01b97632fee9b52f40015e464b8ad7517fbc2764b8d02fdf065b2094d2358d9c33c364882de49d15f213489fb6d452501897c080a02da361cb2134c706358ef0a5b40e260304ee7b161db2ed74c8ee8f7b24518ef2a01b7fa8b7483189a6b00ca979f6a3d71d04e2c766b41400b1f05b89a6037cecaa" ] }, code=UNKNOWN_ERROR, version=6.8.0)
    at makeError (/home/frcs/polygon/js-sdk-examples/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at JsonRpcProvider.getRpcError (/home/frcs/polygon/js-sdk-examples/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:976:25)
    at /home/frcs/nordivo/polygon/js-sdk-examples/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:526:45
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: {
    code: -32000,
    message: 'transaction underpriced: tip needed 30000000000, tip permitted 1000000000'
  },
  payload: {
    method: 'eth_sendRawTransaction',
    params: [
      '0x02f901f48301388204843b9aca00843b9aca1e83228304941a4cc30f2aa0377b0c3bc9848766d90cb440412480b9018428f88a65000d4d2b889f814f2ee2e00869baff56c4a6cc125d57aa373ecbbc06f90513022b889f814f2ee2e00869baff56c4a6cc125d57aa373ecbbc06f90519f511b6840cd3161b348c2d7546d688222f55ac23388db741991016182617ff5333fb646600000000000000000000000000000000000000000000000000000000000000011d2e6793d383d81ce434d528d3dc00128f7272b7fc20ac9884d904b182516cfb1bcfa869ec391d07bb7e78c710711674f518141c3e5dc8573b81961b1d48c5201aa56a0825d0405d8376041f725666df5fe6fb026a1a75c3fe6071fb4748f10621cffb34b147253ab1cc05a9f3f6558bc427a609a3646cdd06e849eb8e63a4d514c666335828b6d1402a43d53baba4adef24c68e6169741d0e4d6fe0caf6e3ad04e874227824bc7c75dc2fc26925ade294f0803c5cb473ee6aa117e967e053e126aa05e5ae9ca71f9b63568b5c7f01b97632fee9b52f40015e464b8ad7517fbc2764b8d02fdf065b2094d2358d9c33c364882de49d15f213489fb6d452501897c080a02da361cb2134c706358ef0a5b40e260304ee7b161db2ed74c8ee8f7b24518ef2a01b7fa8b7483189a6b00ca979f6a3d71d04e2c766b41400b1f05b89a6037cecaa'
    ],
    id: 10,
    jsonrpc: '2.0'
  },
  shortMessage: 'could not coalesce error'
}
```
 - OS version [Ubuntu 22.04]
 - Node version: [20.11]

I am also adding .env values and I have 1 polygon amoy testnet matic in  wallet.
```
const rhsUrl = process.env.RHS_URL ?? 'https://rhs-staging.polygonid.me';
const rpcUrl = process.env.RPC_URL ?? 'https://rpc-amoy.polygon.technology',
const contractAddress = process.env.CONTRACT_ADDRESS ?? '0x1a4cC30f2aA0377b0c3bc9848766D90cb4404124'

```
Can anyone please helpme out on this? 
I have also tested this with the latest release `v1.16.1` and got the same issue.

**Comment by Sshovon** [comment]
The problem was with the rpc url on my end. It's fixed now.  Thanks
