### ISSUE TITLE
Unable to add a specific issuer when created by the issuer node for ZeroKnowledgeProofRequest and issueCredential() in generateProofs()

### ISSUE THREAD

**Issue by KavinduShamalka** [0xPolygonID/js-sdk-examples#32]
=============== generate proofs ===============
=============== user did ===============
did:polygonid:polygon:main:2q2RdhyEQ2aLM7a32oQjqFDQNucc7C3oSbxaQY4Z9t
/Users/mac04/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/storage/memory/merkletree.js:71
        const treeWithMeta = this._data[identifier].find((treeWithInfo) => treeWithInfo.metaInfo.type == mtType);
                                                    ^
TypeError: Cannot read properties of undefined (reading 'find')
    at InMemoryMerkleTreeStorage.getMerkleTreeByIdentifierAndType (/Users/mac04/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/storage/memory/merkletree.js:71:53)
    at IdentityWallet.getDIDTreeModel (/Users/mac04/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/identity/identity-wallet.js:217:51)
    at IdentityWallet.issueCredential (/Users/mac04/js-sdk-examples/node_modules/@0xpolygonid/js-sdk/dist/node/cjs/identity/identity-wallet.js:302:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateProofs (/Users/mac04/js-sdk-examples/index.ts:456:22)
    at async main (/Users/mac04/js-sdk-examples/index.ts:1075:7)
    at async /Users/mac04/js-sdk-examples/index.ts:1125:3

**Comment by vmidyllic** [comment]
Please, can you specify in what way you are adding issuer?
